---
networks:
  lan1:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  lan2:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  wan:
    ipam:
      config:
        - subnet: 192.168.0.0/24

services:
  # LAN1 host
  l1:
    build: frr
    container_name: l1
    networks:
      lan1:
        ipv4_address: 10.0.1.10
    tty: true
    privileged: true

  # Router between LAN1 and WAN
  l2:
    build: frr
    container_name: l2
    volumes:
      - ./certs/ca/ca.crt:/etc/ipsec.d/cacerts/ca.crt
      - ./certs/l2/l2.p12:/etc/ipsec.d/certs/l2.p12
    networks:
      lan1:
        ipv4_address: 10.0.1.11
      wan:
        ipv4_address: 192.168.0.10
    tty: true
    privileged: true


  # Router between LAN2 and WAN
  l3:
    build: frr
    container_name: l3
    volumes:
      - ./certs/ca/ca.crt:/etc/ipsec.d/cacerts/ca.crt
      - ./certs/l3/l3.p12:/etc/ipsec.d/certs/l3.p12
    networks:
      lan2:
        ipv4_address: 10.0.2.11
      wan:
        ipv4_address: 192.168.0.11
    tty: true
    privileged: true

  # LAN2 host
  l4:
    build: frr
    container_name: l4
    networks:
      lan2:
        ipv4_address: 10.0.2.10
    tty: true
    privileged: true

